### ISSUE TITLE
Can someone contact me from Black Forest Labs?

### ISSUE THREAD

**Issue by PierrunoYT** [black-forest-labs/flux#102]
Can someone contact me from Black Forest Labs?

**Comment by jasmine-wood** [comment]
You can try e-mailing them at flux@blackforestlabs.ai.

**Comment by jasmine-wood** [comment]
> Can someone contact me from Black Forest Labs?

You can try e-mailing them at flux@blackforestlabs.ai.

**Comment by PierrunoYT** [comment]
@timudk I send an email regarding to Discord

**Comment by PierrunoYT** [comment]
> > Can someone contact me from Black Forest Labs?
> 
> 
> 
> You can try e-mailing them at flux@blackforestlabs.ai.

They dont reply for a reason.
