### ISSUE TITLE
FLUX.1 [pro]be used for commercial purposes?

### ISSUE THREAD

**Issue by wuhaohezi** [black-forest-labs/flux#16]
Can the images generated using your（or fal.ai/replicate） FLUX.1 [pro]api be used for commercial purposes?

**Comment by JonasLoos** [comment]
In the [API agreement](https://docs.bfl.ml/agreement/), they say

> Users may use the Output for their own personal or commercial purposes, subject to any restrictions set forth herein or in the Flux Service Terms.

**Comment by wuhaohezi** [comment]
In the API agreement, they say
Source Text: 

Translated Text:
Users may use the Output for their own personal or commercial purposes, subject to any restrictions set forth herein or in the Flux Service Terms.

Does this agreement apply equally to the APIs of fal.ai and replicate?> In the [API agreement](https://docs.bfl.ml/agreement/), they say在 API 协议中，他们说
> 
> > Users may use the Output for their own personal or commercial purposes, subject to any restrictions set forth herein or in the Flux Service Terms.用户可以按照本文件或 Flux 服务条款中规定的任何限制条件，自行个人或商业目的使用输出内容。



> In the [API agreement](https://docs.bfl.ml/agreeme

**Comment by wuhaohezi** [comment]
> In the [API agreement](https://docs.bfl.ml/agreement/), they say在 API 协议中，他们说
> 
> > Users may use the Output for their own personal or commercial purposes, subject to any restrictions set forth herein or in the Flux Service Terms.

this agreement applies equally to the APIs provided by them on fal.ai and replicate, right?

**Comment by JonasLoos** [comment]
I guess so, at least they are linked as license on [replicate](https://replicate.com/black-forest-labs/flux-pro)
