### ISSUE TITLE
Installing dependencies based on Conda

### ISSUE THREAD

**Issue by Janko0329** [black-forest-labs/flux#17]
Thank you for sharing this very interesting and useful project!
I noticed that the README file of the project does not mention the steps to install a Conda environment. For the convenience of Anaconda/Miniconda users like myself, could you please consider adding a tutorial for installing dependencies based on Conda?

**Comment by JonasLoos** [comment]
I didn't test it, but for conda the installation should look similar to the venv installation in the readme:

```bash
git clone https://github.com/black-forest-labs/flux
cd flux
conda create -n flux python=3.10
conda activate flux
pip install -e '.[all]'
```
