### ISSUE TITLE
API stopped working 

### ISSUE THREAD

**Issue by EstebanGameDevelopment** [black-forest-labs/flux#174]
I've been working with the cloned repository locally for several weeks and today the same code that was working yesterday no longer works. I've not changed anything on my side.

Here are the steps to reproduce it:

1. Clone the repository
2. Run: python demo_gr.py --name flux-schnell --device cuda --share
3. Make any call to the API: (HTTP POST, Python)
4. Get always **"detail": "Not Found"**

**HTTP POST:**

http://192.168.0.246:7869/generate_image

Raw body:

`{
    "width": 1360,
	"height": 768,
	"num_steps": 4,
	"guidance": 3.5,
	"seed": "Hello!!",
	"prompt": "a magical forest with elves and gnomes dancing around a bondfire",
	"init_image": "None",
	"image2image_strength": 0.8,
	"add_sampling_metadata": true
}`

**Python:**

`client = Client(self.url_flux_image_generation)
                result = client.predict(
                                width=width,
                                height=height,
                                num_steps=steps,
                                guidance=3.5,
                                seed="-1",
                                prompt=description,
                                init_image=None,
                                image2image_strength=0.8,
                                add_sampling_metadata=True,
                                api_name="/generate_image"
                )`

Both API calls were working yesterday. Today they don't work. I've not made changes in my side.

**Comment by jerrymatjila** [comment]
.. even straight forward diffusers code stopped working
Whats going on?

**Comment by EstebanGameDevelopment** [comment]
demo_gr.py API gradio no longer working.
