### ISSUE TITLE
[Wordpress Company Website] hardlink on local IP / image

### ISSUE THREAD

**Issue by ibrainventures** [black-forest-labs/flux#24]
Hi,
thanks for this new chapter of AI generation.

On your website inside the

https://blackforestlabs.ai/our-team/

![grafik](https://github.com/user-attachments/assets/a0c12bf2-5ecc-487a-a762-7f8a04267a15)

There is a hardlinked image on your local Network (192.168.1.78 ..)

**Comment by yumlevi** [comment]
Thanks for flagging it, it's not our local network but it should be gone now.
