### ISSUE TITLE
Looks like image2image wrong code

### ISSUE THREAD

**Issue by ptits** [black-forest-labs/flux#36]
```
        if init_image is not None:
            t_idx = int((1 - image2image_strength) * num_steps)
```

if num_steps = 50 we get only 5 values due to rounding

and image2image_strength is not used anywhere else

**Comment by htoyryla** [comment]
Looks ok to me. When using an init image, one does skip some diffusion timesteps. Here, if image2image is 0, t_idx = num_steps, if 0.5, t_idx is num_steps/2 and so on. 

I have not been able to run this code though, getting stuck at the 44.5GB T5 causing an error.
