### ISSUE TITLE
It is a bit shame that no Gradio demo :(

### ISSUE THREAD

**Issue by FurkanGozukara** [black-forest-labs/flux#5]
I wish you had included a Gradio demo

So we could easily locally install and test locally

Moreover where is requirements.txt file? I would like to install into python venv and run like any other AI model

**Comment by JonasLoos** [comment]
The [installation instructions](https://github.com/black-forest-labs/flux?tab=readme-ov-file#local-installation) actually suggest to install the code into a local venv as a python package. The requirements are listed in [`pyproject.toml`](/black-forest-labs/flux/blob/main/pyproject.toml) and are installed automatically when running the `pip install -e '.[all]'` command.

**Comment by CeterPushing** [comment]
The installation process is pretty straightforward and has a streamlit demo baked into the requirements - I am not sure why one would complain about a Gradio demo - create it yourself.

**Comment by FurkanGozukara** [comment]
@JonasLoos thanks a lot for comment i decided to with SwarmUI since they added support
