### ISSUE TITLE
No Error -> images come out Black

### ISSUE THREAD

**Issue by Gothdir** [black-forest-labs/flux#8]
I use the provided example workflow tried various combinations of smaller T5 and Flux models with recommended settings but all generated images come out black. anyone else experience this?
![image](https://github.com/user-attachments/assets/0961a744-eb9f-4aec-ae9a-d5f416d05cd5)

![image](https://github.com/user-attachments/assets/5928b9a0-a70d-465d-a186-6b4b6efd8fbe)

**Comment by Gothdir** [comment]
Ok Im a moron ignore this

**Comment by JioJe** [comment]
很抱歉打扰到你，我可以知道您是怎么解决这个问题的吗
